id: A608B62B0
title: A Prayer to Khandro Yeshé Tsogyal
type: translation
pechas:
- I7E04554C
- IA3D50BBB
- I98907781
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:51:29.635828
  last_modified_at: 2023-01-04 11:51:29.635842
  collections:
  - Fifteenth Karmapa Series
  - Works of Tibetan Masters
alignment_to_base:
  I7E04554C/BB68: '2320'
  IA3D50BBB/3FA0: '2320'
  I98907781/0390: '2320'
